version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Root where package.json lives
    schedule:
      interval: "weekly" # Options: "daily", "weekly", "monthly"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
